### ISSUE TITLE
我想问一个和项目无关的问题

### ISSUE THREAD

**Issue by CIDE-0409** [Y1-K1NG/poc_exp#2]
作者你好，我可以问问这个漏洞情报是哪里来的嘛。

**Comment by y1hub** [comment]
怎么了 有什么问题吗 也就是公开的漏洞 攻防社区等等 发自我的手机-------- 原始邮件 --------发件人： CIDE-0409 ***@***.***>日期： 2024年3月14日周四 下午3:45收件人： Y1-K1NG/poc_exp ***@***.***>抄送： Subscribed ***@***.***>主    题： [Y1-K1NG/poc_exp] 我想问一个和项目无关的问题 (Issue #2)
作者你好，我可以问问这个漏洞情报是哪里来的嘛。

**Comment by CIDE-0409** [comment]
可以给下是从那个攻防社区来的吗，我是小白，想找到一个靠谱及时的漏洞情报。

**Comment by y1hub** [comment]
抱歉哈 我之前做过的 比如 360 奇安信攻防社区 freebuf等等做的飞书的那种漏洞更新推送（多家推送比较靠谱） 会收到一些工具和漏洞的情报发自我的手机-------- 原始邮件 --------发件人： CIDE-0409 ***@***.***>日期： 2024年3月14日周四 下午4:04收件人： Y1-K1NG/poc_exp ***@***.***>抄送： Y1_K1NG ***@***.***>, Comment ***@***.***>主    题： Re: [Y1-K1NG/poc_exp] 我想问一个和项目无关的问题 (Issue #2)
可以给下是从那个攻防社区来的吗，我是小白，想找到一个靠谱及时的漏洞情报。

**Comment by CIDE-0409** [comment]
好吧，我还想问一个问题，就是今天发的金和viewConTemplate这个漏洞是今年才发现的吗。

**Comment by y1hub** [comment]
最近几个月吧发自我的手机-------- 原始邮件 --------发件人： CIDE-0409 ***@***.***>日期： 2024年3月14日周四 下午4:18收件人： Y1-K1NG/poc_exp ***@***.***>抄送： Y1_K1NG ***@***.***>, Comment ***@***.***>主    题： Re: [Y1-K1NG/poc_exp] 我想问一个和项目无关的问题 (Issue #2)
好吧，我还想问一个问题，就是今天发的金和viewConTemplate这个漏洞是今年才发现的吗。

**Comment by CIDE-0409** [comment]
好的，谢谢大佬。
